package reminder.GUI;
import java.io.IOException;
import java.net.URL;

import javafx.animation.FadeTransition;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;

import javafx.scene.input.DragEvent;
import javafx.scene.input.Dragboard;

import javafx.scene.input.TransferMode;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;

import java.io.File;
import reminder.backbone.CalendarData;
import reminder.backbone.Controller;
import javafx.scene.Node; 
import javafx.scene.control.Label;


/* 
 * This class will control the first scene of the GUI
 * The skeleton was generated by SceneBuilder and I modified it to fit our needs.
 * This scene will take in the path to the .ics file and pass it to the next scene.
 * it allows you to copy and past a full path or drag and drop the file into the text field.
 * not much special here
 * @author Kevin Portillo self-proclaimed coding wizard 🧙
 * 
 */
public class BruhController {
   
    private Stage stage;
	private Scene scene;
	private Parent root;
	
    @FXML
    private Label fileTypeError;
    
    @FXML
    private Button Confirmation;

    @FXML
    private AnchorPane anchorPane;

    @FXML
    private TextField path;
    @FXML
    private Label instructions;


    @FXML
    void onDragOver(DragEvent event) {
        instructions.setVisible(false);
        if (event.getGestureSource() != anchorPane && event.getDragboard().hasFiles()) {
            event.acceptTransferModes(TransferMode.COPY);
        }
        event.consume();
    }

    @FXML
    void dragDrop(DragEvent event) {
        Dragboard db = event.getDragboard();
        boolean success = false;
        if (db.hasFiles()) {
          
            File file = db.getFiles().get(0);
            if(isICSFile(file)){
                path.setText(file.getAbsolutePath());
            }
            else{
                fileTypeError.setVisible(true);
                fileTypeError.setStyle("-fx-text-fill: red;");
                  FadeTransition fade = new FadeTransition();
                    fade.setDuration(javafx.util.Duration.seconds(5));
                    fade.setNode(fileTypeError);
                    fade.setFromValue(1);
                    fade.setToValue(0);
                    fade.play();
               /////
            }
            //System.out.println("Dropped file: " + file.getPath());
            path.setText(file.getPath());
            success = true;
        }
        event.setDropCompleted(success);
        event.consume();
    }
    
    private boolean isICSFile(File file) {
        // Check if the file has a ".ics" extension
        String fileName = file.getName();
        return fileName.toLowerCase().endsWith(".ics");
    }

    /*
     * this method is the submit button it takes reads the paths checks if its an ics
     * if it is it passes us to the next scene along with the Controller object
     */
    @FXML
    void submit(ActionEvent event)throws IOException{
        //when they press submit, we need to get the path from the text field
        Controller c1 = null;
        try {
            //will send us to the second scene
            c1 = new Controller(path.getText());
            CalendarData cd1 = c1.getCalanderData();
            if(cd1 != null){
                //System.out.println("it worked");
                FXMLLoader loader = new FXMLLoader();
                // Use ClassLoader to load the FXML file with a relative path
                URL fxmlUrl = getClass().getClassLoader().getResource("fxml/SecondScene.fxml");
                loader.setLocation(fxmlUrl);
                root = loader.load();
                SecondSceneController scene2Controller = loader.getController();
                scene2Controller.passData(c1);


                //root = FXMLLoader.load(getClass().getResource("Scene2.fxml"));	
                stage = (Stage)((Node)event.getSource()).getScene().getWindow();
                scene = new Scene(root);
                stage.setScene(scene);
                stage.show();    
            }
            else{
               // System.out.println("it didnt work");
            }
        } catch (Exception e) {
            fileTypeError.setVisible(true);
                fileTypeError.setStyle("-fx-text-fill: red;");
                  FadeTransition fade = new FadeTransition();
                    fade.setDuration(javafx.util.Duration.seconds(5));
                    fade.setNode(fileTypeError);
                    fade.setFromValue(1);
                    fade.setToValue(0);
                    fade.play();
               /////
        }
        

        
        
        
    }

    



}
